### ISSUE TITLE
An unspecified error caused the operation to fail - when trying to delete an invoice

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#14]
Application fails with the following exception when I try to delete an invoice:

```
System.Exception: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail. Not a database object.
Version: 2.1.226.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR999.
   at Starcounter.Db.Delete(Object target) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter\Db.cs:line 377
   at InvoiceDemo.InvoiceDetails.Handle(Delete action) in d:\GitHub\Handsoncode\InvoiceDemo\InvoiceDetails.json.cs:line 102
   at InvoiceDemo.InvoiceDetails.JsonByExample.Schema.<.ctor>b__7a(Json pup, Input`1 input) in d:\GitHub\Handsoncode\InvoiceDemo\obj\x64\Debug\InvoiceDetails.json.g.cs:line 0
   at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 225
   at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 247
   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, IntPtr valuePtr, Int32 valueSize) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 100
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter\TransactionManager.cs:line 449
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 27
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 37
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 629
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 473
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 59
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 handlerid, UInt32 groupId, WebSocket ws) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in c:\BuildAgent\work\sc-develop-daily-246\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 668
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR999

```

Steps to reproduce:

1. Create new invoice.
2. Reload page.
3. Select created invoice.
4. Press Delete button.

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Now it fails with another exception:

```
Starcounter.DbException: ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.
```

**Comment by jakubklekota** [comment]
fixed
